name: anime
dependencies:
  - python=3.7
  - more-itertools
  - conda-forge::typing_extensions
  - pandas
  - matplotlib
  - pytorch==1.4.0
  - pip
  - pip:
    - transformers
    - pandarallel
    - pytorch-lightning==0.9.0rc2