name: test-cugraph

channels:
- rapidsai
- nvidia
- conda-forge

dependencies:
  - python=3.7
  - coverage
  - pytest
  - pytest-cov
  - black
  - conda-forge::pre-commit
  - setuptools

  - importlib_metadata
  - numpy
  - networkx
  - pandas
  - conda-forge::python-louvain
  - scipy
  - conda-forge::donfig
  - conda-forge::grblas

  - numba
  - cupy
  - cudf
  - cugraph=0.15.*
  - cudatoolkit=10.1
